#!/usr/bin/env python3
import argparse
import shutil
from pathlib import Path

import pandas as pd


EXPECTED_STUDIES = [
    "infection_study_01",
    "infection_study_04",
    "vaccination_study_04",
    "vaccination_study_06",
    "vaccination_study_09",
]


parser = argparse.ArgumentParser(description="Package clean single-dataset HIPC outputs into reports/current.")
parser.add_argument("--run-root", required=True, help="Directory containing one clean output directory per study.")
parser.add_argument("--report-root", default="reports/current")
parser.add_argument("--replace", action="store_true", help="Replace the report root after building a staging directory.")
args = parser.parse_args()

run_root = Path(args.run_root).resolve()
report_root = Path(args.report_root)
staging_root = report_root.parent / f".{report_root.name}.staging"

if staging_root.exists():
    shutil.rmtree(staging_root)
staging_root.mkdir(parents=True)
(staging_root / "summary/tables").mkdir(parents=True)

summary_tables = {
    "final_annotation_summary.tsv": [],
    "final_annotation_label_counts.tsv": [],
    "lineage_subcluster_evidence.tsv.gz": [],
    "source_disagreement_summary.tsv": [],
    "lineage_panel_status.tsv": [],
    "marker_assignment_feedback.tsv": [],
}

for study in EXPECTED_STUDIES:
    source = run_root / study
    if not source.exists():
        raise SystemExit(f"Missing clean study output: {source}")
    required = [
        source / "report_en.md",
        source / "report_ja.md",
        source / "assets",
        source / "tables",
    ]
    for path in required:
        if not path.exists():
            raise SystemExit(f"Missing required clean output for {study}: {path}")

    target = staging_root / study
    target.mkdir(parents=True)
    shutil.copy2(source / "report_en.md", target / "report_en.md")
    shutil.copy2(source / "report_ja.md", target / "report_ja.md")
    shutil.copytree(source / "assets", target / "assets")
    shutil.copytree(source / "tables", target / "tables")

    for table_name in summary_tables:
        table_path = source / "tables" / table_name
        if not table_path.exists():
            raise SystemExit(f"Missing summary table for {study}: {table_path}")
        summary_tables[table_name].append(pd.read_csv(table_path, sep="\t"))

for table_name, frames in summary_tables.items():
    pd.concat(frames, ignore_index=True).to_csv(staging_root / "summary/tables" / table_name, sep="\t", index=False)

summary_en = [
    "# Current HIPC Annotation Reports",
    "",
    "This bundle was packaged from clean single-dataset outputs. Each dataset directory contains the report, assets, and tables generated by the deterministic annotation pipeline.",
    "",
]
summary_ja = [
    "# Current HIPC Annotation Reports",
    "",
    "この bundle は clean single-dataset output から package したものです。各 dataset directory には deterministic annotation pipeline が生成した report、assets、tables だけを含めています。",
    "",
]
for study in EXPECTED_STUDIES:
    summary_en.append(f"- [{study} English](../{study}/report_en.md), [Japanese](../{study}/report_ja.md)")
    summary_ja.append(f"- [{study} English](../{study}/report_en.md), [Japanese](../{study}/report_ja.md)")
(staging_root / "summary/report_en.md").write_text("\n".join(summary_en) + "\n", encoding="utf-8")
(staging_root / "summary/report_ja.md").write_text("\n".join(summary_ja) + "\n", encoding="utf-8")

if args.replace:
    if report_root.exists():
        shutil.rmtree(report_root)
    staging_root.rename(report_root)
else:
    print(f"Wrote staging report bundle: {staging_root}")
